name: Publish Package

on:
  repository_dispatch:
    types: [release-created]

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
    with:
      test: false
      ref: ${{ github.event.client_payload.ref }}

  publish:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # We don't need to install dependencies since we're only publishing
      # the pre-built artifacts created in the build-test job

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com"
